version: "3.8"

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - ../.env
    volumes:
      - ../logs:/app/logs
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - paypollen-network

  web:
    build:
      context: ../apps/web
      dockerfile: ../../docker/Dockerfile.web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ../apps/web/.env.local
    restart: unless-stopped
    networks:
      - paypollen-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - paypollen-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
      - web
    restart: unless-stopped
    networks:
      - paypollen-network

volumes:
  redis-data:

networks:
  paypollen-network:
    driver: bridge
